update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 33237 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 33237 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 33238 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 33238 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 33239 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 33239 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 33240 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 33240 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 33241 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 33241 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 33242 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 33242 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 33243 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 33243 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 34976 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 34976 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 34977 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 34977 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 34978 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 34978 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 34979 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 34979 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 34980 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 34980 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 34981 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 34981 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 34982 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 34982 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 35569 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 35569 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 35570 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 35570 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 35571 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 35571 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 35572 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 35572 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 35573 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 35573 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 35574 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 35574 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 35575 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 35575 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', updated_user = 'dev_nish', updated_at = NOW() where job_number = 35576 and plant_code = 'H01';
update tms.task_jobs set task_status = 'COMPLETED', task_progress = 'COMPLETED' updated_user = 'dev_nish', updated_at = NOW() where job_number = 35576 and plant_code = 'H01';
